'use client';

import Banner from '@/components/banner';
import styles from './impact-proposition.module.css';
import {
  Sprout,
  Users,
  Globe,
  UserPlus,
  HandHeart,
  Store,
  ShieldCheck,
  Check,
  CheckCircle2,
} from 'lucide-react';

const cn = (names: string) =>
  names
    .split(/\s+/)
    .filter(Boolean)
    .map((name) => styles[name] ?? name)
    .join(' ');

export default function ImpactProposition() {
  return (
    <article className={cn("pbjt impact-proposition-page")}>
      {/* ===================== HERO ===================== */}

      <Banner
        title="Why
              Place-Based
              Just Transition
              is Necessary?"
        imgUrl="/images/impact-proposition/hero-center.jpg"
        textColor="#ffffff"
      />

      {/* ===================== BOARDROOM SECTION ===================== */}
      <section className={cn("pbjt-section pbjt-boardroom")}>
        <div className={cn("pbjt-boardroom__text")}>
          <div className={cn("pbjt-iconchip")}>
            <Sprout size={22} strokeWidth={1.8} />
          </div>
          <h2 className={cn("pbjt-h2")}>Sustainability efforts must go beyond the boardroom.</h2>
          <p className={cn("pbjt-p")}>
            Most sustainability efforts today stop at corporate offices or
            first-tier suppliers. But the real impacts of business, both
            positive and negative, are felt much further down the chain.
            Waste generated by brands is handled locally by sanitation
            workers and communities. Climate stress shows up first as
            heat, water scarcity, pollution, and unsafe working conditions.
            MSMEs and informal enterprises struggle to adopt sustainable
            practices because of limited access to finance, technology,
            and support. Workers experience the risks of transition long
            before companies or investors do.
          </p>
          <p className={cn("pbjt-p")}>
            PBJT bridges this gap by shifting the focus of sustainability
            to where impacts are real, visible, and sustainable.
          </p>
        </div>

        <div className={cn("pbjt-boardroom__media")}>
          <img src="/images/impact-proposition/img137.jpg" alt="Worker handling cement bags" />
          <img src="/images/impact-proposition/img138.jpg" alt="Women workers smiling at a worksite" />
        </div>
      </section>

      {/* ===================== FRAMEWORK SECTION ===================== */}
      <section className={cn("pbjt-section pbjt-framework")}>
        <div className={cn("pbjt-framework__panel")}>
          <div className={cn("pbjt-iconchip pbjt-iconchip--solid")}>
            <Users size={22} strokeWidth={1.8} />
          </div>
          <h2 className={cn("pbjt-h2")}>PBJT as a Value Chain Discovery and Accountability Framework</h2>
          <p className={cn("pbjt-p")}>
            Corporate sustainability reports speak of responsibility,
            ethics, and impact. PBJT asks a different question: how
            do these commitments translate in villages and worksites?
            Using disclosures such as BRSR, PBJT creates a ground-level
            lens for reflection:
          </p>
          <ul className={cn("pbjt-checklist")}>
            <li>
              <CheckCircle2 size={18} strokeWidth={1.8} className={cn("pbjt-checklist__icon")} />
              <span>Do reported labour standards match worker experiences?</span>
            </li>
            <li>
              <CheckCircle2 size={18} strokeWidth={1.8} className={cn("pbjt-checklist__icon")} />
              <span>Are environmental claims visible in local ecosystems?</span>
            </li>
            <li>
              <CheckCircle2 size={18} strokeWidth={1.8} className={cn("pbjt-checklist__icon")} />
              <span>Are informal and last-tier risks acknowledged?</span>
            </li>
          </ul>
        </div>
      </section>

      {/* ===================== INFO BOXES ===================== */}
      <section className={cn("pbjt-info")}>
        <div className={cn("pbjt-info__box pbjt-info__box--icon")}>
          <div className={cn("pbjt-iconchip pbjt-iconchip--solid")}>
            <Globe size={22} strokeWidth={1.8} />
          </div>
          <p className={cn("pbjt-p pbjt-p--muted")}>
            This work is not about auditing companies. It is about
            democratising sustainability language, enabling communities
            to understand what companies promise and to engage,
            negotiate, and seek accountability.
          </p>
        </div>
        <div className={cn("pbjt-info__box")}>
          <p className={cn("pbjt-p pbjt-p--muted")}>
            Our approach aligns with emerging global thinking on responsible
            value chains, including work by the Institute for Human Rights
            and Business and investor discussions that emphasise
            last-mile accountability.
          </p>
        </div>
      </section>

      {/* ===================== BANNER ===================== */}
      <section className={cn("pbjt-banner")}>
        <div className={cn("pbjt-banner__cell pbjt-banner__cell--with-text relative")}>
          <img src="/images/impact-proposition/img139.jpg" alt="Workers in a production facility" />
          <h3 className={cn("pbjt-banner__title")}>
            Critical inputs in<br />villages and<br />production clusters
          </h3>
        </div>
        <div className={cn("pbjt-banner__cell relative")}>
          <img src="/images/impact-proposition/img142.jpg" alt="Agricultural labourer" />
        </div>
        <div className={cn("pbjt-banner__cell relative")}>
          <img src="/images/impact-proposition/img143.jpg" alt="Farmer in a turban" />
        </div>
      </section>

      {/* ===================== BENEFITS ===================== */}
      <section className={cn("pbjt-benefits")}>
        <h3 className={cn("pbjt-benefits__lead")}>
          By working directly in villages and production clusters,
          <br />PBJT helps businesses:
        </h3>

        <div className={cn("pbjt-benefits__grid")}>
          <article className={cn("pbjt-card")}>
            <div className={cn("pbjt-card__icon")}><UserPlus size={26} strokeWidth={1.6} /></div>
            <p className={cn("pbjt-card__body")}>
              <strong>Identify</strong> informal workers, vendors, and
              micro-enterprises linked to their operations
            </p>
          </article>

          <article className={cn("pbjt-card")}>
            <div className={cn("pbjt-card__icon")}><HandHeart size={26} strokeWidth={1.6} /></div>
            <p className={cn("pbjt-card__body")}>
              <strong>Understand</strong> how environmental and social
              risks are distributed locally
            </p>
          </article>

          <article className={cn("pbjt-card")}>
            <div className={cn("pbjt-card__icon")}><Store size={26} strokeWidth={1.6} /></div>
            <p className={cn("pbjt-card__body")}>
              <strong>Support MSMEs</strong> to transition responsibly
            </p>
          </article>

          <article className={cn("pbjt-card")}>
            <div className={cn("pbjt-card__icon")}><ShieldCheck size={26} strokeWidth={1.6} /></div>
            <p className={cn("pbjt-card__body")}>
              <strong>Build stronger</strong>, more ethical, and resilient
              supply chains
            </p>
          </article>
        </div>
      </section>

      {/* ===================== FOOTNOTE ===================== */}
      <footer className={cn("pbjt-footnote")}>
        <Check size={18} strokeWidth={2.2} className={cn("pbjt-footnote__icon")} />
        <p>
          Accountability becomes real when it is visible at the place
          level, not just on paper.
        </p>
      </footer>
    </article>
  );
}

