import styles from "./impact-proposition.module.css";

export const metadata = {
  title: "PBJT – Impact Proposition",
  description: "Why Place-Based Just Transition is necessary",
};

export default function ImpactProposition() {
  return (
    <main className={styles.pbjtWrap}>
      <section className={styles.hero}>
        <div className={styles.heroBg} aria-hidden="true">
          <div />
          <div />
          <div />
          <div />
        </div>

        <div className={styles.heroOverlay} />

        <div className={styles.heroContent}>
          <span className={styles.heroWhy}>Why</span>
          <h1 className={styles.heroTitle}>
            Place-Based <br />
            Just Transition
            <em>is Necessary</em>
          </h1>
        </div>

        <div className={styles.quoteMark} aria-hidden="true">
          &quot;
        </div>
      </section>

      <section className={styles.body}>
        <div className={styles.bodyText}>
          <div className={styles.intro}>
            <p>
              Most sustainability efforts today stop at corporate offices or
              first-tier suppliers. But the real impacts of business; both
              positive and negative are felt much further down the chain.
            </p>

            <p>
              Waste generated by brands is handled locally by sanitation workers
              and communities. Climate stress shows up first as heat, water
              scarcity, pollution, and unsafe working conditions. MSMEs and
              informal enterprises struggle to adopt sustainable practices
              because of limited access to finance, technology, and support.
              Workers experience the risks of transition long before companies
              or investors do. PBJT bridges this gap by shifting the focus of
              sustainability to where impacts are real, visible, and
            </p>
          </div>

          <h2 className={styles.subheading}>
            PBJT as a Value Chain Discovery and Accountability Framework
          </h2>

          <div className={styles.sectionText}>
            <p>
              Corporate sustainability reports speak of responsibility, ethics,
              and impact. PBJT asks a different question: how do these
              commitments translate in villages and worksites?
            </p>

            <p>
              Using disclosures such as Business Responsibility and
              Sustainability Reports (BRSR), PBJT creates a ground-level lens
              for reflection:
            </p>
          </div>

          <ul className={styles.bullets}>
            <li>Do reported labour standards match worker experiences?</li>
            <li>Are environmental claims visible in local ecosystems?</li>
            <li>Are informal and last-tier risks acknowledged?</li>
          </ul>

          <div className={styles.sectionText}>
            <p>
              This work is not about auditing companies. It is about
              democratising sustainability language, enabling communities to
              understand what companies promise and to engage, negotiate, and
              seek accountability.
            </p>

            <p>
              Our approach aligns with emerging global thinking on responsible
              value chains, including work by the Institute for Human Rights and
              Business and investor discussions that emphasise last-mile
              accountability.
            </p>
          </div>
        </div>

        <div className={styles.imageStack} aria-hidden="true">
          <div className={styles.imageCard}>
            <div className={styles.imagePlaceholder}>Image</div>
          </div>
          <div className={styles.imageCard}>
            <div className={styles.imagePlaceholder}>Image</div>
          </div>
        </div>
      </section>

      <section className={styles.banner}>
        <div className={styles.bannerBg} aria-hidden="true">
          <div />
          <div />
          <div />
        </div>

        <div className={styles.bannerOverlay} />

        <div className={styles.bannerLabel}>
          Critical inputs in villages and production clusters
        </div>
      </section>

      <section className={styles.valueSection}>
        <div className={styles.valueBox}>
          <p className={styles.valueHeading}>
            By working directly in villages and production clusters, PBJT helps
            businesses:
          </p>

          <div className={styles.valueItems}>
            <div>Identify informal workers, vendors, and micro-enterprises linked to their operations</div>
            <div>Understand how environmental and social risks are distributed locally</div>
            <div>Support MSMEs to transition responsibly</div>
            <div>Build stronger, more ethical, and resilient supply chains</div>
          </div>
        </div>
      </section>

      <section className={styles.closing}>
        <p>
          Accountability becomes real when it is visible at the place level—not
          just on paper.
        </p>
      </section>
    </main>
  );
}